### ISSUE TITLE
how to check if the data in cache is empty and then load data into the indicated cache?

### ISSUE THREAD

**Issue by marcusau** [long2ice/fastapi-cache#1]
for example,  how to check if there is None data in the cache "test" of the following function section_data?
and how to load new data into it if it is empty.

    def my_key_builder(   func,  namespace: Optional[str] = "",  request: Request = None, response: Response = None, *args,  **kwargs,):
        prefix = FastAPICache.get_prefix()
        cache_key = f"{prefix}:{namespace}:{func.__module__}:{func.__name__}:{args}:{kwargs}"
        return cache_key

    @app.get('/data',response_model=List[Dict])
    @cache(namespace="test", expire=60,key_builder=my_key_builder)
    async def section_data( ):
        data= func('section')
        return data

Thanks a lot

**Comment by long2ice** [comment]
It take effect automatically after you add `cache` decorator, you don't need do some other work

**Comment by marcusau** [comment]
Really? Amazing,

if i set expire=0, that means the cache will never be timeout, then, the cache will be updated if my scheduler re-run the function and fetch the data automatically?

Thanks a lot.

**Comment by long2ice** [comment]
Yes, but set expire=0 means no cache

**Comment by marcusau** [comment]
ok...if so, i should set a very long expiration time, such that whenever the function reload the data, the new dataset would be loaded into the cache and overwrite the old dataset inside, right?

**Comment by long2ice** [comment]
Yes

**Comment by marcusau** [comment]
got it..
Thanks a lot..

i close this comment.

Thanks for your nicely contribution.

Appreciate that much
