### ISSUE TITLE
Cache does not detect differences in headers

### ISSUE THREAD

**Issue by mglowinski93** [long2ice/fastapi-cache#103]
Shouldn't the cache be distinguished based on all the data in the request (like headers and URL), not just the URLs?

Example:
Suppose there is an endpoint `api/users/me` that returns user information based on the token passed in the `Authorization` header.
If I send a request to the above endpoint with a token for `User A`, it will be cached as planned. If I resend a request with token corresponding to `User B`, the request will not be sent and the cached data corresponding to `User A` will be returned.

Is this correct behavior of the package, and shouldn't I expect the cache to distinguish headers in the request?
If so, can I somehow make the cache result be returned only if all the data in the request matches, not just the URL?

**Comment by mkdir700** [comment]
you can try to rewrite`key_buider`.

https://github.com/long2ice/fastapi-cache/blob/73f000a56583556d68f907a9316cc03c4d7115a7/fastapi_cache/key_builder.py#L8-L25

maybe like this:

```python
def custom_key_builder(
    func,
    namespace: Optional[str] = "",
    request: Optional[Request] = None,
    response: Optional[Response] = None,
    args: Optional[tuple] = None,
    kwargs: Optional[dict] = None,
):
    from fastapi_cache import FastAPICache

    prefix = f"{FastAPICache.get_prefix()}:{namespace}:"
    # get the token from the request
    token = request.headers.get("Authorization", "")
    # custom cache key
    cache_key = (
        prefix
        + hashlib.md5(
            f"{func.__module__}:{func.__name__}:{token}:{args}:{kwargs}".encode()
        ).hexdigest()
    )
    return cache_key
```

use `custom_key_builder`

```python
@app.get("/user/{id}")
@cache(key_builder=custom_key_builder)
def user(id: int):
    ...
```

**Comment by mglowinski93** [comment]
Thank you @mkdir700 for a hint.
It worked just great :)
