### ISSUE TITLE
Error "got multiple values for argument 'request'" when I use the request object directly in a post method

### ISSUE THREAD

**Issue by jcdev404** [long2ice/fastapi-cache#113]
Hi all,

We have a POST method, with a complex filtering data structure as the payload which uses 'request' as an input.

It is defined like this:
```python
@app.post(
    path="/my_post_method/",
)
@cache(expire=120, namespace="my_post_method_test”)
async def my_post_method(
    request: Request,
    response: Response,
    myComplexFilterObject: MyComplexFilterClass,
)
…
```

And it is raising this error: `TypeError: my_post_method() got multiple values for argument 'request'`

Apparently the issue comes from `main/fastapi_cache/decorator.py` line 140. Here there is something like this:

```python
if request.method != "GET":
	return await ensure_async_func(request, *args, **kwargs)
```

So what is happening is that by forcing the `request` as an input, if there is another `request` in kwargs, it will raise this issue.

The way how we have fixed was:
```python
if request.method != "GET":
    if kwargs.get("request", None) is not None:
        return await ensure_async_func(*args, **kwargs)
    return await ensure_async_func(request, *args, **kwargs)
```

My questions...

- Do you think this is the right fix?
- Are you planning to allow this sort of methods (post methods with `request` as an input)?

Many thanks!

**Comment by jcdev404** [comment]
Hey... checking all issues, it looks this will fix better my problem: https://github.com/long2ice/fastapi-cache/issues/57

Having said that... I think keeping the code like this can be risky:
```python
if request.method != "GET":
	return await ensure_async_func(request, *args, **kwargs)
```

What if users are using request as a part of theirs  **kwargs? 

Anyway, just trying to help!

:)

**Comment by mkdir700** [comment]
Yes, I agree. It is possible that the request will be passed as an argument.

**Comment by ScholliYT** [comment]
I am also running into this problem (I think). This also happens with POST Endpoints that don't use the request object itself. This error first appeared when updating from 0.1.9 to 0.2.0. 

```py
@app.get("/cache-test/")
@cache(expire=20)
async def cache_test(num: int = 200000000):
    """Compute the sum of all number starting at 1 to num.

    Args:
        num (int, optional): End of the number range. Defaults to 200000000.

    Returns:
        json: response containing the sum of all numbers from 1 to num
    """
    return {"Hello": "Cache!", "Sum": sum(range(num))}


@app.post("/cache-test2")
@cache(expire=60)
async def cache_test2(num: int = 200000000):
    """Compute the sum of all number starting at 1 to num.

    Args:
        num (int, optional): End of the number range. Defaults to 200000000.

    Returns:
        json: response containing the sum of all numbers from 1 to num
    """
    return {"Hello": "Cache!", "Sum": sum(range(num))}
```

First endpoint works fine. Second endpoint throws `TypeError: cache_test2() got multiple values for argument 'num'` from [this](https://github.com/long2ice/fastapi-cache/blob/59a47b7faec895b56dfd6f3d75a286d539dc3cd6/fastapi_cache/decorator.py#L89) line. 

My fix for now is downgrading back to version 0.1.9.

**Comment by XCanG** [comment]
I did local changes to see how it can be fixed and found working solution:
In [`ensure_asunc_func`](https://github.com/long2ice/fastapi-cache/blob/59a47b7faec895b56dfd6f3d75a286d539dc3cd6/fastapi_cache/decorator.py#L75) I added `request` parameter
```py
            async def ensure_async_func(request: Request, *args: P.args, **kwargs: P.kwargs) -> R:
```
Like that.

Then remove it from [block below](https://github.com/long2ice/fastapi-cache/blob/59a47b7faec895b56dfd6f3d75a286d539dc3cd6/fastapi_cache/decorator.py#L142-L143):
```py
            if request.method != "GET":
                return await ensure_async_func(*args, **kwargs)
```
This will result in args remove first positional argument which was result in being `request` and remove double request from this block (it was like `request, request in args, other kwargs` → `request in args become first request, request asterisks become empty`).

In all my tests I didn't find errors, but further testing may needed.

**Comment by mjpieters** [comment]
This can be closed now that #130 has been merged.

**Comment by ppanchal-mobiz** [comment]
@mjpieters, Thank you for the comment. We are eagerly waiting for a release with this fix.

**Comment by RomeoAva** [comment]
I am still facing this issue (probably since no release deployed the fixes)

```
@router.post(
    "/standardize",
)
@cache(expire=60 * 60)
async def standardize_address(address: Address = Body(...)) -> Address:
    """
    Standardize an address.

    Args:
        address (Address): The raw address to standardize.

    Returns:
        Address: The standardized address.
    """
    return address
```
    
When calling the POST endpoint I get `TypeError: standardize_address() got multiple values for argument 'address'`
    
Removing the cache decorator fixes it

**Comment by msamon-synmax** [comment]
Can confirm, I have this issue as well with the below function signature
```python
@router_v1.post("/")
@cache(expire=360)
async def query_events(
    filter: EventFilter,
    limit: int = Query(0, lt=1e6, gt=0),
    skip: int = Query(0, gt=-1),
) -> List[EventResult]:
```
