### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by robert-nix** [long2ice/fastapi-cache#116]
When using `@cache(coder=CustomJsonCoder)`, where `CustomJsonCoder` is a subclass of `fastapi_cache.coder.JsonCoder`, returning a `dict` from a handler causes `TypeError: unhashable type: 'dict'` to raise from #112's hash generation.

e.g.
```py
from fastapi.encoders import jsonable_encoder
from fastapi_cache.coder import JsonCoder


class CustomJsonCoder(JsonCoder):
    @classmethod
    def encode(cls, value):
        return jsonable_encoder(value)

    @classmethod
    def decode(cls, value):
        return value

@router.get("/v1/example")
@cache(expire=60, coder=CustomJsonCoder)
async def get_example():
    return {'message': 'test'}
```

Also FWIW I'm not quite sure why we needed to use this custom coder, I'm just putting this issue in to document the unintended API breakage.

**Comment by mjpieters** [comment]
> Thanks! Could you submit a PR?

The Coder interface is now firmly handling bytes, only, though, so I'm not sure how a PR could help here. ;-)

**Comment by mjpieters** [comment]
I'm closing this issue now; the coder API can only handle bytes. If there was a specific use-case for returning something else, do let us know!
