### ISSUE TITLE
Default key builder does not work with memcached

### ISSUE THREAD

**Issue by MrAngry** [long2ice/fastapi-cache#12]
Memcached does not allow spaces in keys. Thus when using the default key builder with endpoint that has dependencies, a space can be introduced when object is being represented as string. 
Problem example:
```
@router.get("/",
             status_code=200,
             response_model=list)
async def distinct_values(field: str,
                              es: Elasticsearch = Depends(ElasticConnector)):
```
This result in ValidationError

Proposed solution:
```
def mcache_key_builder(
    func,
    namespace: Optional[str] = "",
    request: Request = None,
    response: Response = None,
    *args,
    **kwargs,
):
    prefix = FastAPICache.get_prefix()
    cache_key = f"{prefix}:{namespace}:{func.__module__}:{func.__name__}:{args}:{kwargs}".replace(" ","")
    return cache_key
        ```

**Comment by MrAngry** [comment]
Although a better solution would be to omit dependencies in key creation altogether.

**Comment by long2ice** [comment]
Fixed in dev branch

**Comment by adamantike** [comment]
@long2ice, are you planning to release a new version, with these changes that are currently only available in the dev branch?
