### ISSUE TITLE
feature request: add log on cache hit

### ISSUE THREAD

**Issue by lb-ronyeh** [long2ice/fastapi-cache#136]
need a way to pass key arg to init, for enabling/disabling log on cache hit

**Comment by mjpieters** [comment]
What kind of log did you have in mind?

Would a `X-Cache: HIT` / `X-Cache: MISS` header help here?

**Comment by lb-ronyeh** [comment]
ah, @mjpieters that actually wont work since it sets the cache control on the first cache miss, so we do need a ```X-Cache: HIT / X-Cache: MISS``` 
headers

**Comment by mjpieters** [comment]
> What about provide a event listener?

I was going to add the `X-Cache` header to the decorator; it's a pretty standard header that caching proxies also add (e.g. Varnish).

Would events have advantages here over this here? I'm guessing that in cases where there is no `Response` available (endpoint called by something other than FastAPI) an event would still work, but the headers make it possible to detect caching state in middleware.

**Comment by antont** [comment]
I'm also adding a custom header to tell all the way to the clients if the cache hit or missed, am using it in tests to verify caching and invalidation etc. So just a +1 here.
