### ISSUE TITLE
How to clear cache?

### ISSUE THREAD

**Issue by tom555my** [long2ice/fastapi-cache#16]

**Comment by vietvudanh** [comment]
I am asking this too. And the fact that the `@cache` decorator does not provide a simple key (we have to use key_builder), makes it quite hard in some cases.

**Comment by tom555my** [comment]
Refer to #17. 

You should be able to assign namespace using `@cache` like `@cache(namespace ="example")`. Then, call `FastAPICache.clear(namespace="test")` to clear cache. Please check this [example](https://github.com/long2ice/fastapi-cache/blob/master/examples/main.py).
