### ISSUE TITLE
How to clear cache?

### ISSUE THREAD

**Issue by tom555my** [long2ice/fastapi-cache#17]
Are there any way to **manually** remove the cached result? Many thanks!!

**Comment by long2ice** [comment]
FastAPICache.clear

**Comment by tom555my** [comment]
Hi @long2ice , thanks for the reply. It works for me. It will be much better if we can clear all cache under all namespaces.

**Comment by MarcWarrior** [comment]
> Hi @long2ice , thanks for the reply. It works for me. It will be much better if we can clear all cache under all namespaces.

Hi @tom555my 
I modified the original code in `__init__.py` like this:
```python
async def clear(cls, namespace: str = '', key: str = ''):
    namespace = cls._prefix + ':' + (namespace or '') if not key else ''
    return await cls._backend.clear(namespace, key)
```
and then just call `await FastAPICache.clear()` in the function which you need.
It works good for me to clear all cache under all namespaces.
