### ISSUE TITLE
[Errno 111] Connection refused

### ISSUE THREAD

**Issue by ollita7** [long2ice/fastapi-cache#21]
My application is fully dockerized, it was working fine with fastapi.
Im trying to add cache but It seems to have an error.

Im getting an error trying to create_redis_pool. I tried using localhost, also other ports without any luck.

```py
@app.on_event("startup")
async def startup():
    redis = await aioredis.create_redis_pool("redis://127.0.0.1", encoding="utf8")
    FastAPICache.init(RedisBackend(redis), prefix="fastapi-cache")
```

Also ports are mapped on the `docker-compose.yml`

**Comment by ollita7** [comment]
Nevermind, I aleardy resolved.
The problem was connecting between two services on docker

**Comment by GabrieleCalarota** [comment]
@ollita7 close the issue then ;)

**Comment by AyrtonB** [comment]
Hi @ollita7,

Are you able to share the docker compose configuration that you landed on to get this to work? I've also encountered this issue ([as have others](https://github.com/long2ice/fastapi-cache/issues/67)) and am happy to add some further instructions to the ReadMe if useful.
