### ISSUE TITLE
Include dependencies with PyPi installation

### ISSUE THREAD

**Issue by joeflack4** [long2ice/fastapi-cache#30]
Should not `aioredis`, `memcache`, and `redis` come with the installation of this package, as they are requirements?

Regarding `redis` vs `memcache` and PyPi, this is issue is related: #29

**Comment by mjpieters** [comment]
You need to use one of the named extras when installing the project; e.g. when you want to use the redis backend, use:

```
$ pip install fastapi-cache2[redis]
```

See the [README](https://github.com/long2ice/fastapi-cache#install).
