### ISSUE TITLE
on_event deprecation

### ISSUE THREAD

**Issue by waltzforvenus** [long2ice/fastapi-cache#422]
In the example Readme file @app.on_event("startup") is being used but at the moment it is being deprecated and getting replaced by lifespan functions. 

Ideally the documentation should be updated to compliment the updates on the fastapi library itself.

For more info check:
https://fastapi.tiangolo.com/advanced/events/

**Comment by vicchi** [comment]
Resolved in the `README.md` as part of #426 so closing as `wontfix`.
