### ISSUE TITLE
fastapi用uvicron 多个works启动时 我用内存缓存会有问题

### ISSUE THREAD

**Issue by vvanglro** [long2ice/fastapi-cache#43]
一开始我觉得是_store没有用进程共享变量, 我改成了
```python
from multiprocessing import Manager
class InMemoryBackend:
    _store = Manager().dict()
    _lock = Lock()
```
试了下 还是不行 当请求换了一个进程处理时 还是没共享变量
这是我代码里用的地方https://github.com/vvanglro/fastapi-tortoise-orm/blob/1c7b8bec789ac29455def1e31782a5901d5cb030/coronavirus/main.py#L184
这是改了InMemoryBackend的地方https://github.com/vvanglro/fastapi-tortoise-orm/blob/1c7b8bec789ac29455def1e31782a5901d5cb030/coronavirus/cache.py#L17

**Comment by long2ice** [comment]
内存缓存只适用于单进程，多个worker是多个进程肯定不共享

**Comment by vvanglro** [comment]
> 内存缓存只适用于单进程，多个worker是多个进程肯定

嗯 我用redis了 不折腾了..
