### ISSUE TITLE
Redis version conflict?

### ISSUE THREAD

**Issue by scottyeung** [long2ice/fastapi-cache#441]
Is it possible to bump the current version of Redis to 5.0.8?

Because fastapi-cache2[redis] (0.2.2) depends on redis (>=4.2.0rc1,<5.0.0)
 and no versions of fastapi-cache2 match >0.2.2,<0.3.0, fastapi-cache2[redis] (>=0.2.2,<0.3.0) requires redis (>=4.2.0rc1,<5.0.0).
So, because app depends on both redis (^5.0.8) and fastapi-cache2[redis] (^0.2.2), version solving failed.

**Comment by villqrd** [comment]
@scottyeung same problem. will work if you remove [redis]'s extra

```
pip install fastapi-cache2
```
instead of 
```
pip install "fastapi-cache2[redis]"
```

**Comment by long2ice** [comment]
Updated dependencies

**Comment by vicchi** [comment]
@scottyeung @villqrd The Redis version was bumped to 5.0.8 in 157a9135 and is on the `main` branch but not rolled up for the next release yet.

**Comment by vicchi** [comment]
Closing this as `wontfix` but feel free to re-open if you're still having problems.
