### ISSUE TITLE
Repo maintenance help?

### ISSUE THREAD

**Issue by vicchi** [long2ice/fastapi-cache#450]
Hi @long2ice,

First up I'd like to thank you for creating and maintaining `fastapi-cache`. It's a fantastic addition to the FastAPI ecosystem and one which has helped immensely in my day job.

I've noticed there are several open PRs awaiting review as well as other issues. I know first hand that maintaining an open-source project takes considerable time and effort, especially alongside other commitments.

If you'd be open to it, I'd like to offer my help in maintaining `fastapi-cache` ...  I could help with:

- Reviewing and testing pull requests
- Triaging issues
- Updating documentation
- Writing tests
- Any other areas where you need support

I have a lot of experience with FastAPI and would be 100% committed to continuing to maintain the high standards of the project.

Please let me know if you'd be open to having additional maintainer help and what the next steps might be.

Thanks for reading!

Cheers

Gary

**Comment by long2ice** [comment]
Thanks!

**Comment by vicchi** [comment]
@long2ice For some reason I only just got the collaboration invite from you and of course, it's now expired. Hey ho. Could you resend please?
