### ISSUE TITLE
Avoid response model validation of cache

### ISSUE THREAD

**Issue by m0wer** [long2ice/fastapi-cache#47]
Is there a way of avoiding pydantic response model validation when using cache?

**Comment by m0wer** [comment]
Apparently, a `fastapi.responses.JSONResponse` can be cached only with `fastapi_cache.coder.PickleCoder`.

**Comment by mjpieters** [comment]
This is an older issue and a lot has changed since, but I strongly suspect that #140 will address the issues that remain here.
