### ISSUE TITLE
Testing with FastAPI TestClient - not calling init() first

### ISSUE THREAD

**Issue by jdvalentine** [long2ice/fastapi-cache#54]
I am testing using the FastAPI/Starlette TestClient. This means that @app.on_event("startup") never runs and this is where I am running init(). This means that when the decorator is used during testing, the "You must call init first!" error is thrown.

How do you advise I proceed? What's the simplest way I can skip caching if I'm not running the app with a web server?

Thanks.

**Comment by cyclecycle** [comment]
See [](https://fastapi.tiangolo.com/advanced/testing-events/)

"When you need your event handlers (startup and shutdown) to run in your tests, you can use the TestClient with a with statement"

`with TestClient(app) as client:`

**Comment by jdvalentine** [comment]
Good point. Rather than skipping the caching behaviour when running tests, I should do as you say and make sure that FastAPI's event handlers are used. Thank you.
