### ISSUE TITLE
[Question] How to setup caching globally?

### ISSUE THREAD

**Issue by psdon** [long2ice/fastapi-cache#56]
The current setup is to explicitly call `cache()` decorator on every API endpoints. Any suggestion how to do this globally? Dependency injection seems not to work

**Comment by mjpieters** [comment]
You could create a [custom `APIRoute` subclass](https://fastapi.tiangolo.com/advanced/custom-request-and-route/) to apply the cache decorator to every route:

```python
from typing import Any, Callable

from fastapi.routing import APIRoute


class CachedRoute(APIRoute):
    def __init__(self, path: str, endpoint: Callable[..., Any], *, **kwargs: Any) -> None:
        cache_decorator = cache(...)  # set any path-specific cache configuration here
        super().__init__(path, cache_decorator(endpoint), **kwargs)


app = FastAPI()
app.router.route_class = CachedRoute
```

Now, every time you register a route with `app.get(...)` or any of the other method decorators, the FastAPI-Cache decorator is applied automatically.

I'll see if this isn't a good advanced example for the documentation.
