### ISSUE TITLE
[Question] Method post is caching?

### ISSUE THREAD

**Issue by victorparra96** [long2ice/fastapi-cache#57]
I try cache for fastapi but i not know if post method is caching, or is only for get method

**Comment by long2ice** [comment]
Just for `get`, reference http protocol

**Comment by kishvanchee** [comment]
@victorparra96 you can modify the decorator like this to enable caching for POST https://github.com/long2ice/fastapi-cache/blob/master/fastapi_cache/decorator.py#L53

```python
if request.method not in {"GET", "POST"}:
    return await func(request, *args, **kwargs)
```
I haven't personally experimented with the above, but I have done something similar with https://github.com/a-luna/fastapi-redis-cache

**Comment by aiwhoo** [comment]
Can we move this into the main branch? Definitely seems useful.

**Comment by gegnew** [comment]
agreed, would definitely find this useful

**Comment by mkdir700** [comment]
@long2ice I believe that caching POST requests or any request method can be done because we can leverage the key_builder parameter. What do you think, if it's possible, I would like to submit a pull request for it.

**Comment by mjpieters** [comment]
We should probably consolidate this into a single issue. I've commented on #75, which is the same issue.
