### ISSUE TITLE
Caching an Auth token validation until expiry

### ISSUE THREAD

**Issue by tempcollab** [long2ice/fastapi-cache#59]
I receive an auth token from the frontend with an expiry date in the future. I would like to cache it until expiry date, but the problem is the expiry date cannot be known until the token has been validated once. Here is the example of the function. It currently caches the response for 60 seconds, but I would like it to be `timedelta(token_expiry_timestamp - time.now())`.

```
@cache(namespace="auth", expire=60)
def validate_token(auth_token):
    # first I validate the token
    # then I decode it to obtain user_email and token_expiry_timestamp
    #
    
   def main():
   # some code
   validate_token(auth_token)
```
I was thinking of returning `token_expiry_timestamp` from `validate_token`. Then, in `main()` I'd clear the cache for this specific case if `token_expiry_timestamp` has already passed. Is there a better way to do this?

**Comment by mjpieters** [comment]
Is token validation so expensive that it needs caching? JWT tokens are designed to ensure validation is cheap and I'd not expect to have to cache that process.

Unfortunately, there is currently no way to make expiration work dynamically per request. I'm not certain that we can do this in a clean way either. Given that tokens are small-ish strings, I'd use a different caching library here, to be honest. Even just a dictionary with the token as a key and a tuple of `(datetime, outcome)` as the value would do. Or use your backend directly (e.g. `await redisclient.set(f"token_validation:{token}", outcome, exat=timestamp)` to store, `await redisclient.get(f"token_validation:{token}")` to get the outcome from redis until the expiration time).
