### ISSUE TITLE
[Question]: How would I handle redis failure?

### ISSUE THREAD

**Issue by ashishkjay** [long2ice/fastapi-cache#63]
Wondering how to go about handling Redis failure and keeping app availability

I know that we should treat redis like any other database, but is there any way to handle redis failure or restoring redis cache usage once redis is back up without having to restart the application?

**Comment by mjpieters** [comment]
The cache decorator logs a warning if a backend fails, it is up to the redis client implementation to retry access to Redis.

The Python Redis client has a [rich set of retry configuration options](https://redis-py.readthedocs.io/en/stable/retry.html) you could explore, but I generally would expect the client to just re-connect once your Redis setup is back up and if the cache is still there and fresh FastAPI Cache will continue to use it to serve future requests.

There is no need to restart anything for this to work.
