### ISSUE TITLE
Caching HTMLResponse

### ISSUE THREAD

**Issue by ronbeltran** [long2ice/fastapi-cache#87]
I wanted to cache the html response so that next http requests will be served from cache.
I tried using the @cache decorator to cache the [HTMLResponse](https://fastapi.tiangolo.com/advanced/templates/) but it does not work, does fastapi-cache cache html response?

```
@app.get('/', response_class=HTMLResponse)
@cache(expire=60*60*24)
async def root(request: Request):
    return templates.TemplateResponse('index.html', {
        'request': request,
    })
```

The error i got is:

```
File "/Users/rb/Project/newproject/venv/lib/python3.9/site-packages/fastapi/encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'property' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
```

**Comment by vvanglro** [comment]
@ronbeltran Hi, The cache decorator uses JsonCoder by default, Cached template files are not supported.
But you have two schemes.

1. the first scheme uses jinja2's cache, which already caches 400 templates by default, Details [cache_size](https://github.com/pallets/jinja/blob/a0dd7753d082f8fe6c3225bb3e51de0bbd6fb7e8/src/jinja2/environment.py#L234)

2. Another scheme inherits Coder to implement encode and decode methods

Another scheme example:
```py
from starlette.templating import _TemplateResponse as TemplateResponse


class PickleCoder(Coder):
    @classmethod
    def encode(cls, value: Any):
        if isinstance(value, TemplateResponse):
            value = value.body
        return pickle.dumps(value)

    @classmethod
    def decode(cls, value: Any):
        return pickle.loads(value) 

@app.get('/', response_class=HTMLResponse)
@cache(expire=60*60*24, coder=PickleCoder)
async def root(request: Request):
    return templates.TemplateResponse('index.html', {
        'request': request,
    })
```
It should be noted that, The code uses browser cache through ETag, and in most cases it may not use the cache in redis or other backend.

**Comment by vvanglro** [comment]
@long2ice Hi, are there any plans to support cached templates?

**Comment by mjpieters** [comment]
The `TemplateResponse` class is really just a regular `Response` with `template` and `context` attributes. A better solution would have been to clear the `.template` and `.context` attributes, and / or replace it with a regular `Response()` object (the template and context are only used if the `http.response.debug` extension flag is set, which is normally only done in a test context.

As it stands, the cached response no longer has the correct content type header set, as that's lost when you remove the response object. I'll be looking into reworking how FastAPI-Cache2 handles response objects for #140.

**Comment by mjpieters** [comment]
At any  rate, there was a PR to address this issue directly, so I'm closing this one.
