### ISSUE TITLE
Exclude db session injection in key generation

### ISSUE THREAD

**Issue by reubengann** [long2ice/fastapi-cache#89]
The default key generation doesn't produce a repeatable key when using the Depends method of injecting a new db SQLAlchemy Session into the function. I believe this is a fairly common use case.

```
async def get_thing(
    db: Session = Depends(get_db),
    start_date: date | None = None,
    end_date: date | None = None,
):
```
Since the get_db function returns a unique session, the automatically generated key always differs, and the cache is not utilized. Could the cache decorator be configured to ignore dependency injection arguments? I can make it works with a custom key builder, but I'd rather not have to include that in every route if possible, and make sure I call the variable the exact same thing.

**Comment by mjpieters** [comment]
For now, you'll have to create a custom key builder to exclude injected dependencies like these. I do have plans to make it easier to exclude specific types from key generation by using type annotations, see #129.

**Comment by PaleNeutron** [comment]
I think at least we could improve the default key builder to ignore some kind of arguments, for example, `<class 'sqlalchemy.orm.session.Session'>`

Even in 1.0 we have annotation method to mark a parameter as ignored, depends such as db session should ignored by default.
