### ISSUE TITLE
How to cache `StreamingResponse`?

### ISSUE THREAD

**Issue by mglowinski93** [long2ice/fastapi-cache#97]
Hi,
is there  a way to cache [StreamingResponse](https://fastapi.tiangolo.com/advanced/custom-response/#streamingresponse)?

Currently i get:
```
ValueError: [TypeError("'async_generator' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
```

**Comment by jegork** [comment]
Hello!
I am currently working on implementing a fix for your problem. However there might be a case when the iterator in the StreamingResponse is infinite and that is a problem. Unfortunately, there is no way of detecting whether an iterator is finite so how do we address this?

**Comment by mglowinski93** [comment]
Thank you @jegork for feedback :)

My initial though was adding kind of `timeout` or `max size`, but I'm not sure about the generality of this solution.

**Comment by jegork** [comment]
@mglowinski93 I was also thinking in that direction. 

To preserve the generator nature of the streaming response, it will require either subclassing StreamingResponse and  overwriting its stream_response method or using BackgroundTasks (as far as I see it). The downside of using the background tasks approach is that the generator would have to be run twice.

**Comment by jegork** [comment]
I can draft a solution via subclassing StreamingResponse (I think it will be less error-prone). Regarding the finiteness of the iterator, I can try adding both time and size constraints.

**Comment by mglowinski93** [comment]
I also think, that overwritting 'stream_response' would be better solution.

**Comment by mglowinski93** [comment]
Here is solution: https://github.com/Krukov/cashews/issues/107.
